# Copyright (C) 2020  Christian Berger
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Which Docker image shall be used on the GitLab runner?
image: docker:19.03.3

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://172.17.0.1:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.3-dind

stages:
  - build
  - release
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  except:
    - tags == /^(([0-9]+)\.)?([0-9]+)\.x/
  script:
    - docker build -f ./source_code/Dockerfile ./source_code/

# This section describes what shall be done to deploy artefacts from the project.
semantic_release:
  tags:
    - docker-build
  stage: release
  image: node:13
  variables:
      GITLAB_TOKEN: $ACCESS_TOKEN
  before_script:
      - npm install @semantic-release/gitlab
 # only:
    #refs:
    #- master
    # This matches maintenance branches
   # - /^(([0-9]+)\.)?([0-9]+)\.x/

  script:
    - npx semantic-release
    
deploy:
  tags:
    - docker-build
  stage: deploy
  
  script:
    - cd source_code
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"
  only:
    refs:
    - tags == /^(([0-9]+)\.)?([0-9]+)\.x/
